spring:
  liquibase:
    contexts: dev

  mail:
    host: smtp.mailtrap.io
    port: 587
    username: ${mailtrap.user}
    password: ${mailtrap.password}
    properties:
      mail.debug: true

logging:
  level:
    org.hibernate: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG