complexity:
  CognitiveComplexMethod:
    active: true
    threshold: 15
  ComplexCondition:
    active: true
    threshold: 4
  NestedScopeFunctions:
    active: true
    threshold: 1
    functions:
      - 'kotlin.apply'
      - 'kotlin.run'
      - 'kotlin.with'
      - 'kotlin.let'
      - 'kotlin.also'
  LongParameterList:
    active: true
    functionThreshold: 6
    constructorThreshold: 10
    ignoreDefaultParameters: true
    ignoreDataClasses: true
    ignoreAnnotatedParameter: [ Column ]

exceptions:
  NotImplementedDeclaration:
    active: true
  ObjectExtendsThrowable:
    active: true
  TooGenericExceptionThrown:
    active: true
    excludes: [ '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/androidUnitTest/**', '**/androidInstrumentedTest/**', '**/jsTest/**', '**/iosTest/**' ]
    exceptionNames:
      - 'Error'
      - 'Exception'
      - 'RuntimeException'
      - 'Throwable'

naming:
  BooleanPropertyNaming:
    active: true
    allowedPattern: '^(is|has|are)'
  FunctionMinLength:
    active: true
    minimumFunctionNameLength: 2
  NonBooleanPropertyPrefixedWithIs:
    active: true

potential-bugs:
  CastNullableToNonNullableType:
    active: true
  CastToNullableType:
    active: true
  MissingPackageDeclaration:
    active: true
    excludes: [ '**/*.kts' ]
  UnnecessaryNotNullCheck:
    active: true

style:
  AlsoCouldBeApply:
    active: true
  BracesOnIfStatements:
    active: true
    singleLine: 'never'
    multiLine: 'always'
  BracesOnWhenStatements:
    active: true
    singleLine: 'necessary'
    multiLine: 'consistent'
  DestructuringDeclarationWithTooManyEntries:
    active: true
    maxDestructuringEntries: 5
  ForbiddenAnnotation:
    active: true
    annotations:
      - reason: 'it is a java annotation. Use `Suppress` instead.'
        value: 'java.lang.SuppressWarnings'
      - reason: 'it is a java annotation. Use `kotlin.Deprecated` instead.'
        value: 'java.lang.Deprecated'
      - reason: 'it is a java annotation. Use `kotlin.annotation.MustBeDocumented` instead.'
        value: 'java.lang.annotation.Documented'
      - reason: 'it is a java annotation. Use `kotlin.annotation.Target` instead.'
        value: 'java.lang.annotation.Target'
      - reason: 'it is a java annotation. Use `kotlin.annotation.Retention` instead.'
        value: 'java.lang.annotation.Retention'
      - reason: 'it is a java annotation. Use `kotlin.annotation.Repeatable` instead.'
        value: 'java.lang.annotation.Repeatable'
      - reason: 'Kotlin does not support @Inherited annotation, see https://youtrack.jetbrains.com/issue/KT-22265'
        value: 'java.lang.annotation.Inherited'
  ForbiddenComment:
    active: true
    comments:
      - reason: 'Forbidden FIXME todo marker in comment, please fix the problem.'
        value: 'FIXME:'
      - reason: 'Forbidden STOPSHIP todo marker in comment, please address the problem before shipping the code.'
        value: 'STOPSHIP:'
      - reason: 'Forbidden TODO todo marker in comment, please do the changes.'
        value: 'TODO:'
    allowedPatterns: ''
  NewLineAtEndOfFile:
    active: false
  SpacingBetweenPackageAndImports:
    active: true
  TrailingWhitespace:
    active: true
  UnusedImports:
    active: true
  ReturnCount:
    active: true
    max: 3
    excludedFunctions:
      - 'equals'
    excludeLabeled: false
    excludeReturnFromLambda: true
    excludeGuardClauses: true